asynchronous data conditional rendering
henzbori/react-todo pull request #7
Opened 2024-12-25 05:05 UTC by henzbori

2025-01-01 20:58 UTC, pavel6767 commented on src/App.jsx
> +        () => resolve({data: { todoList: JSON.parse(localStorage.getItem("savedTodoList")) } }),
I think this also needs to handle the case of `savedTodoList` being null. right now, if this happens `todoList` will be set to `null` and the application will break since the `TodoList` component expects the prop to be an array type

2025-01-01 20:59 UTC, pavel6767 commented on src/App.jsx
> +    })
Right now it may not matter, but just in case, please add a `catch` clause, if anything just to add a console log as the assignment says

`.catch(error => console.log(‘error’, {error}))`

2025-01-01 21:11 UTC, pavel6767 requested changes
Looks good. Please address comments

2025-01-01 23:04 UTC, henzbori commented on src/App.jsx
> +        () => resolve({data: { todoList: JSON.parse(localStorage.getItem("savedTodoList")) } }),
added "|| []"
would it fix it?

2025-01-01 23:05 UTC, henzbori commented on src/App.jsx
> +    })
added the catch at the end

2025-01-01 23:12 UTC, henzbori commented
Pavel please check the changes if i can merge it to main. I am not sure how to contact you about the changes

2025-01-02 02:00 UTC, pavel6767 approved these changes
LGTM

2025-01-08 20:37 UTC, merged